FROM node:20-bullseye AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build


FROM node:20-bullseye

WORKDIR /app

# 👇 Use local dependency instead of global install
RUN npm install serve
RUN npm config set registry https://registry.npmjs.org/

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["npx", "serve", "-s", "dist", "-l", "3000"]