FROM node:20-bullseye AS builder
#  more stable than slim

WORKDIR /app

# Update npm to avoid bug
RUN npm install -g npm@10

COPY package*.json ./

# Clean + reliable install
RUN npm ci --no-audit --no-fund

COPY . .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build


FROM node:20-bullseye

WORKDIR /app

# Use lightweight static server
RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]