services:
  db:
    image: postgres:15
    container_name: chat_db
    ports:
      - 8080:8080
    volumes:
      - chat_db_vol:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat_backend
    ports:
      - 8000:8000
    env_file:
      - .env
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat_frontend
    ports:
      - 80:80
volumes:
  chat_db_vol: