FROM python:3.11

WORKDIR /app
COPY . .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# incase of any errors in production usage
RUN python manage.py collectstatic --noinput

# RUN python manage.py migrate

EXPOSE 8000

CMD ["gunicorn", "coreBackend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]