apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-svc
  namespace: chatapp
spec:
  type: NodePort
  selector:
    app: chatapp
    tier: front
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30088
